FROM centos:8 
LABEL maintainer="admin@idwrx.com"
LABEL description="Puppet server"

RUN dnf -y clean all && dnf -y update && dnf -y autoremove && dnf -y clean all
RUN dnf install -y https://yum.puppetlabs.com/puppet-release-el-8.noarch.rpm
RUN dnf install -y --setopt=tsflags=nodocs puppetserver-6.8.0-1.el8

EXPOSE 8140/tcp


VOLUME ["/etc/puppetlabs", "/opt/puppetlabs/server/data/puppetserver", "/var/log/puppetlabs/puppetserver"]

CMD ["/opt/puppetlabs/bin/puppetserver", "foreground"]
